name: 🐛 Bug Report
description: Create a report to help improve this plugin
title: "[Bug] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Hello 👋 Thank you for submitting an issue.

  - type: dropdown
    id: addon
    attributes:
      label: Addon
      description: Please select the addon related to this issue
      options:
        - "No specific addon – This bug report is related to Webtools Core"
        - "Webtools Core - Sitemap Addon"
        - "Webtools Pro - Redirects Addon"
        - "Webtools Pro - Links Addon"
    validations:
      required: true

  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what happened
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to reproduce the behavior
      description: Please provide detailed steps to reproduce the issue
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: What should have happened instead?
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
      placeholder: Drag and drop screenshots here or paste image URLs

  - type: textarea
    id: code-snippets
    attributes:
      label: Code snippets
      description: If applicable, add code samples to help explain your problem.
      render: javascript
      placeholder: Add your code here

  - type: input
    id: nodejs-version
    attributes:
      label: Node.js version
      description: Please ensure you are using the Node LTS version
      placeholder: e.g., v18.17.0
    validations:
      required: true

  - type: dropdown
    id: package-manager
    attributes:
      label: Package manager
      description: Which package manager are you using?
      options:
        - NPM
        - Yarn
        - Pnpm
    validations:
      required: true

  - type: input
    id: strapi-version
    attributes:
      label: Strapi version
      placeholder: e.g., 4.15.5
    validations:
      required: true

  - type: input
    id: plugin-version
    attributes:
      label: Plugin version
      placeholder: e.g., 1.2.3
    validations:
      required: true

  - type: input
    id: database
    attributes:
      label: Database
      placeholder: e.g., PostgreSQL, MySQL, SQLite
    validations:
      required: true

  - type: input
    id: operating-system
    attributes:
      label: Operating system
      placeholder: e.g., macOS 13.6, Windows 11, Ubuntu 22.04
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
      placeholder: Any additional information that might be helpful
