/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
import webtoolsAddonLinks from "@pluginpal/webtools-addon-links/strapi-admin";
import webtoolsAddonSitemap from "@pluginpal/webtools-addon-sitemap/strapi-admin";
import webtools from "@pluginpal/webtools-core/strapi-admin";
import i18N from "@strapi/plugin-i18n/strapi-admin";
import usersPermissions from "@strapi/plugin-users-permissions/strapi-admin";
import { renderAdmin } from "@strapi/strapi/admin";

import customisations from "../../src/admin/app.js";

renderAdmin(document.getElementById("strapi"), {
  customisations,

  plugins: {
    "webtools-addon-links": webtoolsAddonLinks,
    "webtools-addon-sitemap": webtoolsAddonSitemap,
    webtools: webtools,
    i18n: i18N,
    "users-permissions": usersPermissions,
  },
});
