/**
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  webtoolsSidebar: [
    {
      type: "category",
      collapsed: false,
      label: "🚀 Getting Started",
      items: [
        "getting-started/installation",
        "getting-started/usage",
        "getting-started/url-pattern",
        "getting-started/url-alias",
        "getting-started/api-permissions",
        "getting-started/admin-permissions",
        "getting-started/troubleshooting",
      ],
    },
    {
      type: "category",
      collapsed: false,
      label: "📦 API",
      items: [
        "api/rest",
        "api/graphql",
      ],
    },
    {
      type: "category",
      collapsed: false,
      label: "📟 CLI",
      items: [
        "cli/install",
        "cli/enable",
        "cli/setup-license",
      ],
    },
    {
      type: "category",
      collapsed: false,
      label: "🔌 Addons",
      items: [
        "addons/introduction",
        {
          type: "link",
          label: "Sitemap addon",
          href: '/addons/sitemap',
        },
        {
          type: "link",
          label: "Redirects addon",
          href: '/addons/redirects',
        },
        {
          type: "link",
          label: "Links addon",
          href: '/addons/links',
        },
      ],
    },
    {
      type: "category",
      collapsed: false,
      label: "⚙️ Configuration",
      items: [
        "configuration/introduction",
        "configuration/default-pattern",
        "configuration/website-url",
        "configuration/slugify",
        "configuration/unique-per-locale",
      ],
    },
    // {
    //   type: "category",
    //   collapsed: false,
    //   label: "♻️ Upgrading",
    //   items: [
    //     "upgrading/generic-update",
    //   ],
    // },
  ],

  webtoolsSitemapSidebar: [
    {
      type: "link",
      label: "⬅️ Back to Webtools Core docs",
      href: "/addons",
    },
    {
      type: "category",
      collapsed: false,
      label: "🔌 Sitemap addon",
      items: [
        {
          type: "category",
          collapsed: false,
          label: "🚀 Getting Started",
          items: [
            "addons/sitemap/getting-started/introduction",
            "addons/sitemap/getting-started/installation",
            "addons/sitemap/getting-started/usage",
            "addons/sitemap/getting-started/multilingual",
            "addons/sitemap/getting-started/sitemap-index",
            "addons/sitemap/getting-started/robots-txt",
            "addons/sitemap/getting-started/cli",
            "addons/sitemap/getting-started/api-permissions",
            "addons/sitemap/getting-started/admin-permissions",
            "addons/sitemap/getting-started/troubleshooting",
          ],
        },
        {
          type: "category",
          collapsed: false,
          label: "⚙️ Settings",
          items: [
            "addons/sitemap/settings/introduction",
            "addons/sitemap/settings/hostname",
            "addons/sitemap/settings/hostname-overrides",
            "addons/sitemap/settings/exclude-drafts",
            "addons/sitemap/settings/include-homepage",
            "addons/sitemap/settings/default-language-url-type",
          ],
        },
        {
          type: "category",
          collapsed: false,
          label: "🔧 Configuration",
          items: [
            "addons/sitemap/configuration/introduction",
            "addons/sitemap/configuration/cron",
            "addons/sitemap/configuration/limit",
            "addons/sitemap/configuration/xsl",
            "addons/sitemap/configuration/auto-generate",
          ],
        },
      ],
    },
  ],

  webtoolsRedirectsSidebar: [
    {
      type: "link",
      label: "⬅️ Back to Webtools Core docs",
      href: "/addons",
    },
    {
      type: "category",
      collapsed: false,
      label: "🔀 Redirects addon",
      items: [
        {
          type: "category",
          collapsed: false,
          label: "🚀 Getting Started",
          items: [
            "addons/redirects/getting-started/introduction",
            "addons/redirects/getting-started/installation",
            "addons/redirects/getting-started/usage",
            "addons/redirects/getting-started/api-permissions",
            "addons/redirects/getting-started/admin-permissions",
          ],
        },
        {
          type: "category",
          collapsed: false,
          label: "📦 API",
          items: [
            "addons/redirects/api/rest",
          ],
        },
        {
          type: "category",
          collapsed: false,
          label: "🔧 Configuration",
          items: [
            "addons/redirects/configuration/introduction",
            "addons/redirects/configuration/auto-generate",
            "addons/redirects/configuration/default-status-code",
          ],
        },
      ],
    },
  ],

  webtoolsLinksSidebar: [
    {
      type: "link",
      label: "⬅️ Back to Webtools Core docs",
      href: "/addons",
    },
    {
      type: "category",
      collapsed: false,
      label: "🔗 Links addon",
      items: [
        {
          type: "category",
          collapsed: false,
          label: "🚀 Getting Started",
          items: [
            "addons/links/getting-started/introduction",
            "addons/links/getting-started/installation",
            "addons/links/getting-started/custom-field",
            "addons/links/getting-started/ckeditor",
          ],
        },
        {
          type: "category",
          collapsed: false,
          label: "📦 API",
          items: [
            "addons/links/api/links-format",
          ],
        },
      ],
    },
  ],
};

module.exports = sidebars;
