npmScopes:
  pluginpal:
    npmPublishRegistry: https://npm.pluginpal.io
    npmRegistryServer: https://npm.pluginpal.io
    npmAlwaysAuth: true
    npmAuthIdent: "token"
    npmAuthToken: "WEBTOOLS-4F4D6E86-270C-461A-B1FB-F58B5A707793"
