name: Deploy Docs

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: startsWith(github.event.release.name, 'docs@')
    environment:
      name: docs.pluginpal.io
      url: https://docs.pluginpal.io/webtools
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: actions/setup-node@v4
        with:
          node-version: '14'

      - name: Build a Docker image
        run: |
          cd packages/docs
          docker build \
            -t docs-webtools:latest .
          docker save -o ../../docs-webtools-latest.tar docs-webtools:latest

      - name: Transfer the Docker image to the Dokku server
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_CI_USERNAME }}
          password: ${{ secrets.SSH_CI_PASSWORD }}
          source: docs-webtools-latest.tar
          target: /var/lib/dokku/data/storage/docs/docker-images

      - name: Deploy the Dokku app based on the Docker image
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_CI_USERNAME }}
          password: ${{ secrets.SSH_CI_PASSWORD }}
          script_stop: true
          script: |
            sudo docker load -i /var/lib/dokku/data/storage/docs/docker-images/docs-webtools-latest.tar
            DOCS_WEBTOOLS_LATEST_IMAGE=$(sudo docker images --format "{{.ID}}" docs-webtools:latest)
            sudo docker tag docs-webtools:latest docs-webtools:$DOCS_WEBTOOLS_LATEST_IMAGE
            dokku git:from-image docs-webtools docs-webtools:$DOCS_WEBTOOLS_LATEST_IMAGE
            sudo docker system prune --all --force
